dist: trusty
sudo: required

language: generic

# work-a-round for https://github.com/travis-ci/travis-ci/issues/8317
addons:
  apt:
    packages:
    - libsdl2-dev

before_install:
    # Required by Buildozer Android
    # https://buildozer.readthedocs.io/en/latest/installation.html#android-on-ubuntu-14-10-64bit
    - sudo apt-get update -q
    - sudo pip install --upgrade cython==0.21
    - sudo dpkg --add-architecture i386
    - sudo apt-get install build-essential ccache git lib32stdc++6 lib32z1 lib32z1-dev python2.7 python2.7-dev openjdk-7-jdk unzip zlib1g-dev zlib1g:i386
    # Required by Kivy
    # https://kivy.org/docs/installation/installation-linux.html#dependencies-with-sdl2
    - sudo apt-get install python-pip libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev

env:
    matrix:
        - SCRIPT_COMMAND="./travis/script_linux.sh"
        - SCRIPT_COMMAND="./travis/script_android.sh"

script:
    # runs in parallel
    - (eval "$SCRIPT_COMMAND")

deploy:
  provider: releases
  api_key: ${GH_TOKEN_FROM_ENV}
  file: 
    - "bin/runcalculator-debug.apk"
    - "bin/runcalculator-release-unsigned.apk"
  skip_cleanup: true
  on:
    tags: true

# how to get GH_TOKEN?
# https://blog.wyrihaximus.net/2015/09/github-auth-token-on-travis/
# auto release on tags
