dist: trusty
sudo: required

language: generic

services:
  - docker

before_install:
    # https://github.com/jedie/kivy-buildozer-docker
    - docker pull jedie/buildozer

script:
    - ls -la
    - cd runcalculator
    - ls -la
    - docker run -t jedie/buildozer -v ${PWD}:/buildozer/ buildozer --verbose android release

# https://docs.travis-ci.com/user/deployment/releases/
deploy:
  provider: releases
  api_key: ${GH_TOKEN_FROM_ENV}
  file:
    - "bin/runcalculator-debug.apk"
    - "bin/runcalculator-release-unsigned.apk"
  skip_cleanup: true
  on:
    tags: true

# how to get GH_TOKEN?
# https://blog.wyrihaximus.net/2015/09/github-auth-token-on-travis/
# auto release on tags
