sudo: required
dist: trusty
language: python
python:
    - "2.7"
before_install:
    - sudo apt-get install -y python-opengl python-gst0.10 python-enchant python-dev
    - sudo apt-get install -y gstreamer0.10-plugins-good libgl1-mesa-dev-lts-quantal libgles2-mesa-dev-lts-quantal
    - sudo add-apt-repository -y ppa:kivy-team/kivy-daily
    - sudo apt-get update
    - sudo apt-get install -y python-kivy
    - pip install pip
    - pip install setuptools
    - pip install wsgiref
    - pip install --upgrade Cython==0.23
    - sudo apt-get update
    - sudo apt-get install -y build-essential lib32z1 lib32bz2-1.0 python2.7-dev openjdk-7-jdk unzip zlib1g-dev
    - sudo apt-get install -y lib32ncurses5 
    - sudo dpkg --add-architecture i386
    - sudo apt-get install -y lib32stdc++6 
    - git clone https://github.com/kivy/buildozer.git
    - cd buildozer
    - sudo python setup.py install
    - cd ..
    - sudo rm -rf .buildozer
script:
    - cd runcalculator
    - buildozer android debug
    - buildozer android release

# using kivy-daily: python-kivy-1.9.2-0 version and CI testing ;)
# dist: trusty means Trusty Beta (14.04) which have new Kivy

# buildozer deps for Ubuntu 14.10
# for more see: http://buildozer.readthedocs.io/en/latest/installation.html

# trick needed?
# http://askubuntu.com/questions/423083/cant-run-dpkg-add-architecture-i386-on-12-04-64-bit-to-run-eclipse-adt

# maybe this: libz1:i386 not needed??? ;/ desperate to download Trusty Beta to local

# auto build with buildozer
# ---

deploy:
  provider: releases
  api_key: ${GH_TOKEN_FROM_ENV}
  file: 
    - "bin/runcalculator-debug.apk"
    - "bin/runcalculator-release-unsigned.apk"
  skip_cleanup: true
  on:
    tags: true

# how to get GH_TOKEN?
# https://blog.wyrihaximus.net/2015/09/github-auth-token-on-travis/
# auto release on tags
