dist: trusty
sudo: required

language: generic

services:
  - docker

before_install:
    # https://github.com/jedie/kivy-buildozer-docker
    - docker pull jedie/buildozer

script:
    # some version information:
    - docker run -v ${PWD}:/buildozer/ -t jedie/buildozer python --version
    - docker run -v ${PWD}:/buildozer/ -t jedie/buildozer pip freeze
    - docker run -v ${PWD}:/buildozer/ -t jedie/buildozer cython --version
    - docker run -v ${PWD}:/buildozer/ -t jedie/buildozer buildozer --version

    - cd runcalculator
    - ls -la

    # build .apk via buildozer
    - docker run -v ${PWD}:/buildozer/ -t jedie/buildozer buildozer --verbose android release
    - docker run -v ${PWD}:/buildozer/ -t jedie/buildozer buildozer --verbose android debug

# https://docs.travis-ci.com/user/deployment/releases/
deploy:
  provider: releases
  api_key: ${GH_TOKEN_FROM_ENV}
  file:
    - "bin/runcalculator-debug.apk"
    - "bin/runcalculator-release-unsigned.apk"
  skip_cleanup: true
  on:
    tags: true

# how to get GH_TOKEN?
# https://blog.wyrihaximus.net/2015/09/github-auth-token-on-travis/
# auto release on tags
